In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=5)

In [3]:
A = np.array([[3, 3],
              [2, 5],
              [0 ,6]])
B_T = np.array([[3, 2, 3],
                [2, 6, 1]])
m, n = A.shape

In [4]:
tableau0 = np.empty((n, m+n+1))
tableau0[:, :m] = B_T
tableau0[:, m:m+n] = np.identity(n)
tableau0[:, -1] = 1

In [5]:
tableau0

array([[ 3.,  2.,  3.,  1.,  0.,  1.],
       [ 2.,  6.,  1.,  0.,  1.,  1.]])

In [6]:
tableau1 = np.empty((m, n+m+1))
tableau1[:, :m] = np.identity(m)
tableau1[:, m:m+n] = A
tableau1[:, -1] = 1

In [7]:
tableau1

array([[ 1.,  0.,  0.,  3.,  3.,  1.],
       [ 0.,  1.,  0.,  2.,  5.,  1.],
       [ 0.,  0.,  1.,  0.,  6.,  1.]])

In [8]:
basic_vars0 = np.arange(m, m+n)
basic_vars0

array([3, 4])

In [9]:
basic_vars1 = np.arange(0, m)
basic_vars1

array([0, 1, 2])

In [10]:
init_pivot = 1

In [11]:
pivot = init_pivot

In [12]:
ratios = tableau0[:, -1] / tableau0[:, pivot]
ratios

array([ 0.5    ,  0.16667])

In [13]:
row_min = ratios.argmin()
row_min

1

In [14]:
basic_vars0[row_min]

4

In [15]:
tableau0[row_min, :] /= tableau0[row_min, pivot]

In [16]:
tableau0

array([[ 3.     ,  2.     ,  3.     ,  1.     ,  0.     ,  1.     ],
       [ 0.33333,  1.     ,  0.16667,  0.     ,  0.16667,  0.16667]])

In [17]:
for i in range(tableau0.shape[0]):
    if i != row_min:
        tableau0[i, :] -= tableau0[row_min, :] * tableau0[i, pivot]

In [18]:
tableau0

array([[ 2.33333,  0.     ,  2.66667,  1.     , -0.33333,  0.66667],
       [ 0.33333,  1.     ,  0.16667,  0.     ,  0.16667,  0.16667]])

In [19]:
basic_vars0[row_min], pivot = pivot, basic_vars0[row_min]

In [20]:
basic_vars0

array([3, 1])

In [21]:
basic_vars0[row_min]

1

In [22]:
pivot


4

In [23]:
pivot == init_pivot

False

In [24]:
tableau1

array([[ 1.,  0.,  0.,  3.,  3.,  1.],
       [ 0.,  1.,  0.,  2.,  5.,  1.],
       [ 0.,  0.,  1.,  0.,  6.,  1.]])

In [25]:
ratios = tableau1[:, -1] / tableau1[:, pivot]
row_min = ratios.argmin()
row_min


2

In [26]:
tableau1[row_min, :] /= tableau1[row_min, pivot]


In [27]:

tableau1

array([[ 1.     ,  0.     ,  0.     ,  3.     ,  3.     ,  1.     ],
       [ 0.     ,  1.     ,  0.     ,  2.     ,  5.     ,  1.     ],
       [ 0.     ,  0.     ,  0.16667,  0.     ,  1.     ,  0.16667]])

In [28]:
ind = np.ones(tableau1.shape[0], dtype=bool)
ind[row_min] = False
tableau1[ind, :] -= tableau1[row_min, :] * tableau1[ind, :][:, [pivot]]

In [29]:
tableau1

array([[ 1.     ,  0.     , -0.5    ,  3.     ,  0.     ,  0.5    ],
       [ 0.     ,  1.     , -0.83333,  2.     ,  0.     ,  0.16667],
       [ 0.     ,  0.     ,  0.16667,  0.     ,  1.     ,  0.16667]])

In [30]:
basic_vars1[row_min], pivot = pivot, basic_vars1[row_min]

In [31]:
pivot

2

In [32]:
basic_vars1

array([0, 1, 4])

In [33]:
pivot == init_pivot

False

In [34]:
tableau0

array([[ 2.33333,  0.     ,  2.66667,  1.     , -0.33333,  0.66667],
       [ 0.33333,  1.     ,  0.16667,  0.     ,  0.16667,  0.16667]])

In [35]:
ratios = tableau0[:, -1] / tableau0[:, pivot]
row_min = ratios.argmin()
row_min

0

In [36]:
tableau0[row_min, :] /= tableau0[row_min, pivot]
ind = np.ones(tableau0.shape[0], dtype=bool)
ind[row_min] = False
tableau0[ind, :] -= tableau0[row_min, :] * tableau0[ind, :][:, [pivot]]

In [37]:
tableau0

array([[ 0.875 ,  0.    ,  1.    ,  0.375 , -0.125 ,  0.25  ],
       [ 0.1875,  1.    ,  0.    , -0.0625,  0.1875,  0.125 ]])

In [38]:
basic_vars0[row_min], pivot = pivot, basic_vars0[row_min]

In [39]:
pivot

3

In [40]:
pivot == init_pivot

False

In [41]:
tableau1

array([[ 1.     ,  0.     , -0.5    ,  3.     ,  0.     ,  0.5    ],
       [ 0.     ,  1.     , -0.83333,  2.     ,  0.     ,  0.16667],
       [ 0.     ,  0.     ,  0.16667,  0.     ,  1.     ,  0.16667]])

In [42]:
ratios = tableau1[:, -1] / tableau1[:, pivot]
row_min = ratios.argmin()
row_min

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


1

In [43]:
tableau1[:, pivot]

array([ 3.,  2.,  0.])

In [44]:
with np.errstate(divide='ignore'):
    ratios = tableau1[:, -1] / tableau1[:, pivot]

In [45]:
ratios

array([ 0.16667,  0.08333,      inf])

In [46]:
tableau1[row_min, :] /= tableau1[row_min, pivot]
ind = np.ones(tableau1.shape[0], dtype=bool)
ind[row_min] = False
tableau1[ind, :] -= tableau1[row_min, :] * tableau1[ind, :][:, [pivot]]

In [47]:
tableau1

array([[ 1.     , -1.5    ,  0.75   ,  0.     ,  0.     ,  0.25   ],
       [ 0.     ,  0.5    , -0.41667,  1.     ,  0.     ,  0.08333],
       [ 0.     ,  0.     ,  0.16667,  0.     ,  1.     ,  0.16667]])

In [48]:
basic_vars1[row_min], pivot = pivot, basic_vars1[row_min]

In [49]:
pivot

1

In [50]:
pivot == init_pivot

True

In [51]:
basic_vars0

array([2, 1])

In [52]:
basic_vars1

array([0, 3, 4])

In [53]:
basic_vars0[basic_vars0 < m]

array([2, 1])

In [54]:
basic_vars1[basic_vars1 >= m]

array([3, 4])

In [55]:
tableau0[basic_vars0 < m, -1]

array([ 0.25 ,  0.125])

In [56]:
tableau1[basic_vars1 >= m, -1]

array([ 0.08333,  0.16667])

In [57]:
x = np.zeros(m)
x[basic_vars0[basic_vars0 < m]] = tableau0[basic_vars0 < m, -1]
x /= x.sum()

In [58]:
x

array([ 0.     ,  0.33333,  0.66667])

In [59]:
y = np.zeros(n)
y[basic_vars1[basic_vars1 >= m] - m] = tableau1[basic_vars1 >= m, -1]
y /= y.sum()

In [60]:
y

array([ 0.33333,  0.66667])

In [61]:
(x, y)

(array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667]))

In [62]:
def min_ratio_test(tableau, pivot):
    ind_nonpositive = tableau[:, pivot] <= 0
    with np.errstate(divide='ignore', invalid='ignore'):
        ratios = tableau[:, -1] / tableau[:, pivot]
    ratios[ind_nonpositive] = np.inf
    row_min = ratios.argmin()
    return row_min

In [63]:
def pivoting(tableau, pivot, pivot_row):
    """
    Perform a pivoting step.
    
    Modify `tableau` in place (and return its view).
    
    """
    # Row indices except pivot_row
    ind = np.ones(tableau.shape[0], dtype=bool)
    ind[pivot_row] = False
    
    # Store the values in the pivot column, except for row_min
    # Made 2-dim by np.newaxis
    multipliers = tableau[ind, pivot, np.newaxis]
    
    # Update the tableau
    tableau[pivot_row, :] /= tableau[pivot_row, pivot]
    tableau[ind, :] -= tableau[pivot_row, :] * multipliers
    
    return tableau

In [64]:
def lemke_howson_tbl(tableau0, tableau1, basic_vars0, basic_vars1, init_pivot):
    m, n = tableau1.shape[0], tableau0.shape[0]
    tableaux = (tableau0, tableau1)
    basic_vars = (basic_vars0, basic_vars1)
    init_player = int((basic_vars[0]==init_pivot).any())
    players = [init_player, 1 - init_player]

    pivot = init_pivot

    while True:
        for i in players:
            # Determine the leaving variable
            row_min = min_ratio_test(tableaux[i], pivot)
            
            # Pivoting step: modify tableau in place
            pivoting(tableaux[i], pivot, row_min)
            
            # Update the basic variables and the pivot
            basic_vars[i][row_min], pivot = pivot, basic_vars[i][row_min]
            
            if pivot == init_pivot:
                break
        else:
            continue
        break

    out_dtype = np.result_type(*tableaux)
    out = np.zeros(m+n, dtype=out_dtype)
    for i, (start, num) in enumerate(zip((0, m), (m, n))):
        ind = basic_vars[i] < start + num if i == 0 else start <= basic_vars[i]
        out[basic_vars[i][ind]] = tableaux[i][ind, -1]
        
    return out

In [65]:
def normalize(unnormalized, m, n):
    normalized = np.empty(m+n)
    for (start, num) in zip((0, m), (m, n)):
        s = unnormalized[start:start+num].sum()
        if s != 0:
            normalized[start:start+num] = unnormalized[start:start+num] / s
        else:
            normalized[start:start+num] = 0
    return normalized[:m], normalized[m:]

In [66]:
def lemke_howson(A, B_T, init_pivot=0, return_tableaux=False):
    m, n = A.shape
    tableaux = (np.hstack((B_T, np.identity(n), np.ones((n, 1)))),
                np.hstack((np.identity(m), A, np.ones((m, 1)))))
    basic_vars = (np.arange(m, m+n), np.arange(0, m))
    unnormalized = lemke_howson_tbl(*tableaux, *basic_vars, init_pivot)
    normalized = normalize(unnormalized, m, n)
    if return_tableaux:
        return normalized, tableaux, basic_vars
    return normalized

In [67]:
init_pivot = 1
x, y = lemke_howson(A, B_T, init_pivot)
print("Nash equilibrium found\n", (x, y))

Nash equilibrium found
 (array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667]))


In [68]:
lemke_howson(A, B_T, init_pivot, return_tableaux=True)

((array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667])),
 (array([[ 0.875 ,  0.    ,  1.    ,  0.375 , -0.125 ,  0.25  ],
         [ 0.1875,  1.    ,  0.    , -0.0625,  0.1875,  0.125 ]]),
  array([[ 1.     , -1.5    ,  0.75   ,  0.     ,  0.     ,  0.25   ],
         [ 0.     ,  0.5    , -0.41667,  1.     ,  0.     ,  0.08333],
         [ 0.     ,  0.     ,  0.16667,  0.     ,  1.     ,  0.16667]])),
 (array([2, 1]), array([0, 3, 4])))

In [69]:
def lemke_howson_all(A, B_T):
    m, n = A.shape
    k = 0
    NEs = []
    basic_vars_list = []
    player = (m <= n)
    init_pivot = k
    actions, tableaux, basic_vars = \
        lemke_howson(A, B_T, init_pivot, return_tableaux=True)
    NEs.append(actions)
    basic_vars_list.append(np.sort(basic_vars[player]))

    for a in range(m+n):
        if a == k:
            continue
        init_pivot = a
        actions, tableaux, basic_vars = \
            lemke_howson(A, B_T, init_pivot, return_tableaux=True)
        basic_vars_sorted = np.sort(basic_vars[player])
        for arr in basic_vars_list:
            if np.array_equal(basic_vars_sorted, arr):
                break
        else:
            NEs.append(actions)
            basic_vars_list.append(basic_vars_sorted)

            unnormalized = \
                lemke_howson_tbl(*tableaux, *basic_vars, init_pivot=k)
            NEs.append(normalize(unnormalized, m, n))
            basic_vars_list.append(np.sort(basic_vars[player]))
            
    return NEs

In [70]:
lemke_howson_all(A, B_T)

[(array([ 1.,  0.,  0.]), array([ 1.,  0.])),
 (array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667])),
 (array([ 0.8,  0.2,  0. ]), array([ 0.66667,  0.33333]))]

In [71]:
payoff_matrix_3_7 = np.array([[3, 3, 0], [4, 0, 1], [0, 4, 5]])
lemke_howson_all(payoff_matrix_3_7, payoff_matrix_3_7)

[(array([ 0.,  0.,  1.]), array([ 0.,  0.,  1.]))]

In [72]:
def pivoting_int(tableau, pivot, pivot_row, prev_pivot_el):
    """
    Perform a pivoting step with integer input data.
    
    Modify `tableau` in place (and return its view).
    
    """
    # Row indices except pivot_row
    ind = np.ones(tableau.shape[0], dtype=bool)
    ind[pivot_row] = False
    
    # Store the values in the pivot column, except for row_min
    # Made 2-dim by np.newaxis
    multipliers = tableau[ind, pivot, np.newaxis]
    
    # Update the tableau
    tableau[ind, :] *= tableau[pivot_row, pivot]
    tableau[ind, :] -= tableau[pivot_row, :] * multipliers
    tableau[ind, :] //= prev_pivot_el  # Floor division: return int
    
    return tableau

In [73]:
def lemke_howson_tbl_int(tableau0, tableau1, basic_vars0, basic_vars1, init_pivot):
    m, n = tableau1.shape[0], tableau0.shape[0]
    tableaux = (tableau0, tableau1)
    basic_vars = (basic_vars0, basic_vars1)
    init_player = int((basic_vars[0]==init_pivot).any())
    players = [init_player, 1 - init_player]

    pivot = init_pivot
    prev_pivot_els = np.ones(2, dtype=np.int_)

    while True:
        for i in players:
            # Determine the leaving variable
            row_min = min_ratio_test(tableaux[i], pivot)
            
            # Pivoting step: modify tableau in place
            pivoting_int(tableaux[i], pivot, row_min, prev_pivot_els[i])
            
            # Backup the pivot element
            prev_pivot_els[i] = tableaux[i][row_min, pivot]
            
            # Update the basic variables and the pivot
            basic_vars[i][row_min], pivot = pivot, basic_vars[i][row_min]
            
            if pivot == init_pivot:
                break
        else:
            continue
        break

    out = np.zeros(m+n, dtype=np.int_)
    for i, (start, num) in enumerate(zip((0, m), (m, n))):
        ind = basic_vars[i] < start + num if i == 0 else start <= basic_vars[i]
        out[basic_vars[i][ind]] = tableaux[i][ind, -1]
        
    return out

In [74]:
import sympy

In [75]:
def normalize_rational(unnormalized, m, n):
    """
    Normalize the integer array `unnormalized` with ratioal numbers.
    
    """
    normalized = np.empty(m+n, np.object_)
    for (start, num) in zip((0, m), (m, n)):
        s = unnormalized[start:start+num].sum()
        if s != 0:
            for k in range(start, start+num):
                normalized[k] = sympy.Rational(sympy.S(unnormalized[k]), sympy.S(s))
        else:
            normalized[start:start+num] = sympy.Rational(0)
    return normalized[:m], normalized[m:]

In [76]:
def lemke_howson_int(A, B_T, init_pivot=0, rational=False, return_tableaux=False):
    m, n = A.shape
    tableaux = (np.hstack((B_T, np.identity(n, dtype=np.int_), np.ones((n, 1), dtype=np.int_))),
                np.hstack((np.identity(m, dtype=np.int_), A, np.ones((m, 1), dtype=np.int_))))
    basic_vars = (np.arange(m, m+n), np.arange(0, m))
    unnormalized = lemke_howson_tbl_int(*tableaux, *basic_vars, init_pivot)
    if rational:
        normalized = normalize_rational(unnormalized, m, n)
    else:
        normalized = normalize(unnormalized, m, n)
    if return_tableaux:
        return normalized, tableaux, basic_vars
    return normalized

In [77]:
def lemke_howson_all_int(A, B_T, rational=False):
    m, n = A.shape
    k = 0
    NEs = []
    basic_vars_list = []
    player = (m <= n)
    init_pivot = k
    actions, tableaux, basic_vars = \
        lemke_howson_int(A, B_T, init_pivot, rational=rational, return_tableaux=True)
    NEs.append(actions)
    basic_vars_list.append(np.sort(basic_vars[player]))

    for a in range(m+n):
        if a == k:
            continue
        init_pivot = a
        actions, tableaux, basic_vars = \
            lemke_howson_int(A, B_T, init_pivot, rational=rational, return_tableaux=True)
        basic_vars_sorted = np.sort(basic_vars[player])
        for arr in basic_vars_list:
            if np.array_equal(basic_vars_sorted, arr):
                break
        else:
            NEs.append(actions)
            basic_vars_list.append(basic_vars_sorted)

            unnormalized = \
                lemke_howson_tbl_int(*tableaux, *basic_vars, init_pivot=k)
            if rational:
                normalized = normalize_rational(unnormalized, m, n)
            else:
                normalized = normalize(unnormalized, m, n)
            NEs.append(normalized)
            basic_vars_list.append(np.sort(basic_vars[player]))
            
    return NEs

In [78]:
lemke_howson_int(A, B_T, init_pivot=1)

(array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667]))

In [79]:
lemke_howson_int(A, B_T, init_pivot=1, return_tableaux=True)

((array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667])),
 (array([[14,  0, 16,  6, -2,  4],
         [ 3, 16,  0, -1,  3,  2]]), array([[ 12, -18,   9,   0,   0,   3],
         [  0,   6,  -5,  12,   0,   1],
         [  0,   0,   2,   0,  12,   2]])),
 (array([2, 1]), array([0, 3, 4])))

In [80]:
lemke_howson_int(A, B_T, init_pivot=1, rational=True)

(array([0, 1/3, 2/3], dtype=object), array([1/3, 2/3], dtype=object))

In [81]:
lemke_howson_int(A, B_T, init_pivot=0, rational=True)

(array([1, 0, 0], dtype=object), array([1, 0], dtype=object))

In [82]:
lemke_howson_all_int(A, B_T)

[(array([ 1.,  0.,  0.]), array([ 1.,  0.])),
 (array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667])),
 (array([ 0.2,  0.8,  0. ]), array([ 0.66667,  0.33333]))]

In [83]:
lemke_howson_all_int(A, B_T, rational=True)

[(array([1, 0, 0], dtype=object), array([1, 0], dtype=object)),
 (array([0, 1/3, 2/3], dtype=object), array([1/3, 2/3], dtype=object)),
 (array([1/5, 4/5, 0], dtype=object), array([2/3, 1/3], dtype=object))]

In [84]:
def min_ratio_test_no_tie_breaking(tableau, pivot, test_col, argmins, num_argmins):
    idx = 0
    i = argmins[idx]
    if tableau[i, pivot] > 0:
        min_ratio = tableau[i, test_col] / tableau[i, pivot]
    else:
        min_ratio = np.inf
    for k in range(1, num_argmins):
        i = argmins[k]
        if tableau[i, pivot] <= 0:
            continue
        ratio = tableau[i, test_col] / tableau[i, pivot]
        if ratio > min_ratio:
            continue
        elif ratio < min_ratio:
            min_ratio = ratio
            idx = 0
        elif ratio == min_ratio:
            idx += 1
        argmins[idx] = k
    return idx + 1

In [85]:
def lex_min_ratio_test(tableau, pivot, slack_start):
    num_rows = tableau.shape[0]
    argmins = np.arange(num_rows)
    num_argmins = num_rows
    
    num_argmins = min_ratio_test_no_tie_breaking(tableau, pivot, -1, argmins, num_argmins)
    if num_argmins == 1:
        return argmins[0]
    
    for j in range(slack_start, slack_start+num_rows):
        if j == pivot:
            continue
        num_argmins = min_ratio_test_no_tie_breaking(tableau, pivot, j, argmins, num_argmins)
        if num_argmins == 1:
            break
    return argmins[0]

In [86]:
2/3

0.6666666666666666

In [87]:
1 - 1/3

0.6666666666666667

In [88]:
1 - 1/3 == 2/3

False

In [89]:
def lemke_howson_tbl_int_lex_min(tableau0, tableau1, basic_vars0, basic_vars1, init_pivot):
    m, n = tableau1.shape[0], tableau0.shape[0]
    tableaux = (tableau0, tableau1)
    basic_vars = (basic_vars0, basic_vars1)
    init_player = int((basic_vars[0]==init_pivot).any())
    players = [init_player, 1 - init_player]

    pivot = init_pivot
    prev_pivot_els = np.ones(2, dtype=np.int_)
    slack_starts = (m, 0)

    while True:
        for i in players:
            # Determine the leaving variable
            row_min = lex_min_ratio_test(tableaux[i], pivot, slack_starts[i])
            
            # Pivoting step: modify tableau in place
            pivoting_int(tableaux[i], pivot, row_min, prev_pivot_els[i])
            
            # Backup the pivot element
            prev_pivot_els[i] = tableaux[i][row_min, pivot]
            
            # Update the basic variables and the pivot
            basic_vars[i][row_min], pivot = pivot, basic_vars[i][row_min]
            
            if pivot == init_pivot:
                break
        else:
            continue
        break

    out = np.zeros(m+n, dtype=np.int_)
    for i, (start, num) in enumerate(zip((0, m), (m, n))):
        ind = basic_vars[i] < start + num if i == 0 else start <= basic_vars[i]
        out[basic_vars[i][ind]] = tableaux[i][ind, -1]
        
    return out

In [90]:
def lemke_howson_int_lex_min(A, B_T, init_pivot=0, rational=False, return_tableaux=False):
    m, n = A.shape
    tableaux = (np.hstack((B_T, np.identity(n, dtype=np.int_), np.ones((n, 1), dtype=np.int_))),
                np.hstack((np.identity(m, dtype=np.int_), A, np.ones((m, 1), dtype=np.int_))))
    basic_vars = (np.arange(m, m+n), np.arange(0, m))
    unnormalized = lemke_howson_tbl_int_lex_min(*tableaux, *basic_vars, init_pivot)
    if rational:
        normalized = normalize_rational(unnormalized, m, n)
    else:
        normalized = normalize(unnormalized, m, n)
    if return_tableaux:
        return normalized, tableaux, basic_vars
    return normalized

In [91]:
def lemke_howson_all_int_lex_min(A, B_T, rational=False):
    m, n = A.shape
    k = 0
    NEs = []
    basic_vars_list = []
    player = (m <= n)
    init_pivot = k
    actions, tableaux, basic_vars = \
        lemke_howson_int_lex_min(A, B_T, init_pivot, rational=rational, return_tableaux=True)
    NEs.append(actions)
    basic_vars_list.append(np.sort(basic_vars[player]))

    for a in range(m+n):
        if a == k:
            continue
        init_pivot = a
        actions, tableaux, basic_vars = \
            lemke_howson_int_lex_min(A, B_T, init_pivot, rational=rational, return_tableaux=True)
        basic_vars_sorted = np.sort(basic_vars[player])
        for arr in basic_vars_list:
            if np.array_equal(basic_vars_sorted, arr):
                break
        else:
            NEs.append(actions)
            basic_vars_list.append(basic_vars_sorted)

            unnormalized = \
                lemke_howson_tbl_int_lex_min(*tableaux, *basic_vars, init_pivot=k)
            if rational:
                normalized = normalize_rational(unnormalized, m, n)
            else:
                normalized = normalize(unnormalized, m, n)
            NEs.append(normalized)
            basic_vars_list.append(np.sort(basic_vars[player]))
            
    return NEs

In [92]:
C = np.array([[3, 3],
              [2, 5],
              [0 ,6]])
D_T = np.array([[3, 2, 3],
                [3, 6, 1]])

In [93]:
lemke_howson_all(C, D_T)

[(array([ 1.,  0.,  0.]), array([ 1.,  0.])),
 (array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667])),
 (array([ 0.,  0.,  0.]), array([ 0.,  0.]))]

In [94]:
lemke_howson_all_int_lex_min(C, D_T)

[(array([ 0.     ,  0.33333,  0.66667]), array([ 0.33333,  0.66667]))]

In [95]:
E = np.array([[3, 3],
              [5, 2],
              [6 ,0]])
F_T = np.array([[3, 6, 1],
                [3, 2, 3]])

In [96]:
lemke_howson_all_int_lex_min(E, F_T)

[(array([ 1.,  0.,  0.]), array([ 0.,  1.])),
 (array([ 0.     ,  0.33333,  0.66667]), array([ 0.66667,  0.33333])),
 (array([ 1.,  0.,  0.]), array([ 0.33333,  0.66667]))]

In [97]:
eps = 0.01
D_T_eps = np.array([[3 / (1 + eps), 2 / (1 + eps), 3 / (1 + eps)],
                    [3 / (1 + eps**2), 6 / (1 + eps**2), 1 / (1 + eps**2)]])
F_T_eps = np.array([[3 / (1 + eps**2), 2 / (1 + eps**2), 3 / (1 + eps**2)],
                    [3 / (1 + eps), 6 / (1 + eps), 1 / (1 + eps)]])

In [98]:
lemke_howson_all(C, D_T_eps)

[(array([ 0.     ,  0.32897,  0.67103]), array([ 0.33333,  0.66667]))]

In [99]:
lemke_howson_all(C, F_T_eps)

[(array([ 1.,  0.,  0.]), array([ 1.,  0.])),
 (array([ 0.     ,  0.33773,  0.66227]), array([ 0.33333,  0.66667])),
 (array([ 0.99259,  0.00741,  0.     ]), array([ 0.66667,  0.33333]))]